swagger: '2.0'
info:
  version: 1.0.0
  title: MyPet API
  description: >
    La API que expone el servidor MyPet

host: localhost:8080
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth:
    post:
      description: Obtener un token de autenticación
      parameters:
        - description: Credenciales de autenticación
          in: body
          name: body
          required: true
          schema:
            properties:
              username:
                type: string
              password:
                type: string
                format: password
      produces:
        - application/json
      responses:
        200:
          description: Conexión correcta
          schema:
            properties:
              token:
                type: string
                description: Token de login. Se deberá usar en todos los llamados a la api.
        400:
          $ref: "#/responses/BadRequest"
        401:
          $ref: "#/responses/Unauthorized"
  /user:
    get:
      description: Información de usuario
      parameters:
        - $ref: "#/parameters/Token"
      responses:
        200:
          description: Datos de usuario
          schema:
            type: object
            properties:
              name:
                type: string
    post:
      description: Crear un usuario
      parameters:
        - description: Datos de usuario
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UserData"
      responses:
        200:
          $ref: "#/responses/Success"
        400:
          $ref: "#/responses/BadRequest"
        401:
          $ref: "#/responses/Unauthorized"
    put:
      description: Modificar un usuario
      parameters:
        - description: Datos de usuario
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UserData"
        - $ref: "#/parameters/Token"
      responses:
        200:
          $ref: "#/responses/Success"
        400:
          $ref: "#/responses/BadRequest"
        401:
          $ref: "#/responses/Unauthorized"
  /pet:
    post:
      description: Crear una mascota
      parameters:
        - $ref: "#/parameters/Token"
        - description: Datos de la mascota
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/PetData"
      responses:
        200:
          description: Mascota creada correctamente
          schema:
            $ref: "#/definitions/PetData"
        400:
          $ref: "#/responses/BadRequest"
        401:
          $ref: "#/responses/Unauthorized"
    get:
      description: Obtiene todas tus mascotas
      parameters:
        - $ref: "#/parameters/Token"
      responses:
        200:
          description: Todas tus mascotas
          schema:
            type: array
            items:
              $ref: "#/definitions/PetData"
        401:
          $ref: "#/responses/Unauthorized"
  /pet/{id}:
    parameters:
      - description: Identificador de la mascota
        name: id
        in: path
        type: string
        required: true
      - $ref: "#/parameters/Token"
    get:
      description: Obtener datos acerca de una mascota
      responses:
        200:
          description: Datos de mascota
          schema:
            $ref: "#/definitions/PetData"
        400:
          $ref: "#/responses/BadRequest"
        401:
          $ref: "#/responses/Unauthorized"
    put:
      description: Modificar datos acerca de una mascota
      parameters:
        - description: Datos de la mascota
          in: body
          name: body
          schema:
            $ref: "#/definitions/PetData"
      responses:
        200:
          description: Datos de mascota
          schema:
            $ref: "#/definitions/PetData"
        400:
          $ref: "#/responses/BadRequest"
        401:
          $ref: "#/responses/Unauthorized"
      
definitions:
  UserData:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
        format: password
  PetData:
    type: object
    properties:
      name:
        type: string
        description: Nombre
      id:
        type: string
        description: Identificador
  Error:
    type: object
    properties:
      error:
        type: object
        properties:
          description:
            type: string
            description: Representación en texto del error
          code:
            type: integer
            description: Código de error
parameters:
  Token:
    description: Token de autenticación
    in: query
    name: token
    type: string
    required: true
responses:
  Success:
    description: Acción realizada correctamente
    schema:
      type: object
      properties:
        success:
          description: Mensaje
  Unauthorized:
    description: Error de autenticación
    schema:
      $ref: "#/definitions/Error"
  BadRequest:
    description: No se especificaron todos los parametros necesarios
    schema:
      $ref: "#/definitions/Error"
  